[package]
name = "abbegm"
version = "0.2.1"
license = "BSD-2-Clause"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"RoboHouse <robohouse@robovalley.com>",
]

description = "externally guided motion for ABB industrial robots"
keywords = ["robotics", "abb", "egm", "motion", "industrial"]
categories = ["science::robotics", "network-programming"]
repository = "https://github.com/robohouse-delft/abbegm-rs"
documentation = "https://docs.rs/abbegm"
readme = "README.md"

edition = "2018"

[features]
default = ["nalgebra", "tokio"]

[dependencies]
nalgebra = { version = "0.21.0", optional = true }
prost = "0.6.1"
tokio = { version = "0.2.17", optional = true, features = ["udp"] }

[dev-dependencies]
assert2 = "0.2.1"
structopt = "0.3.0"
tokio = { version = "0.2.18", features = ["udp", "dns", "rt-threaded", "macros"] }
